insert into Inventory (SKUID,PRODUCTNAME,PRODUCTLABEL,INVENTORYONHAND,MINQTYREQ,PRICE) values (10,'BEER','CARLSBERG',500,200,160);
insert into Inventory (SKUID,PRODUCTNAME,PRODUCTLABEL,INVENTORYONHAND,MINQTYREQ,PRICE) values (11,'BEER','BUD',1000,300,190);
insert into Inventory (SKUID,PRODUCTNAME,PRODUCTLABEL,INVENTORYONHAND,MINQTYREQ,PRICE) values (12,'WHISKEY','BLENDERS PRIDE',300,100,950);
insert into Inventory (SKUID,PRODUCTNAME,PRODUCTLABEL,INVENTORYONHAND,MINQTYREQ,PRICE) values (13,'RUM','OLD MONK',400,150,420);