CREATE TABLE VENDOR (
    VENDORID BIGINT PRIMARY KEY,
    VENDORNAME varchar(100),
    VENDORCONTACTNO BIGINT,
    VENDOREMAIL varchar(100),
    VENDORUSERNAME varchar(100),
	VENDORADDRESS varchar(100)
 
);